using Rat = global::Lovelace.Rational.Rational;

namespace Lovelace.Symbolics;

/// <summary>
/// Gröbner bases over Q[x1..xn] (Buchberger's algorithm, correct-first). Monomial orders:
/// Lex, GrLex, GrRevLex (the existing MonomialOrder). Later optimizations (Gebauer–Möller
/// criteria, F4/F5, modular methods) are explicitly deferred until the correctness
/// infrastructure around polynomial algorithms is complete.
/// </summary>
public static class Groebner
{
    /// <summary>Computes a reduced Gröbner basis of the ideal generated by the inputs.</summary>
    public static List<Polynomial> Basis(IEnumerable<Polynomial> generators, MonomialOrder order)
    {
        var input = generators.Where(g => !g.IsZero).ToList();
        if (input.Count == 0)
            return new List<Polynomial>();

        var cmp = new MonomialComparer(order);
        var basis = new List<Polynomial>(input.Select(g => Monic(g)));
        var pairs = new List<(int, int)>();
        for (int i = 0; i < basis.Count; i++)
            for (int j = i + 1; j < basis.Count; j++)
                pairs.Add((i, j));

        var seen = new HashSet<(int, int)>(pairs);
        while (pairs.Count > 0)
        {
            Lovelace.Abstractions.Cancellation.ThrowIfCancellationRequested();
            var (i, j) = pairs[0];
            pairs.RemoveAt(0);
            var s = SPolynomial(basis[i], basis[j], cmp);
            if (s.IsZero)
                continue;
            var r = ReduceBy(s, basis, cmp);
            if (r.IsZero)
                continue;
            int k = basis.Count;
            basis.Add(Monic(r));
            for (int t = 0; t < k; t++)
            {
                if (seen.Add((t, k)))
                    pairs.Add((t, k));
            }
        }
        return Interreduce(basis, cmp);
    }

    /// <summary>Reduces p to a normal form against the basis (the remainder of multivariate division).</summary>
    public static Polynomial Reduce(Polynomial p, IReadOnlyList<Polynomial> basis, MonomialOrder order)
    {
        var cmp = new MonomialComparer(order);
        return ReduceBy(p, basis, cmp);
    }

    /// <summary>
    /// Eliminates the given variables: a lex-ordered basis intersected with the polynomials
    /// that no longer mention the eliminated variables (elimination theorem).
    /// </summary>
    public static List<Polynomial> Eliminate(
        IEnumerable<Polynomial> generators, IEnumerable<Symbol> eliminated, MonomialOrder order = MonomialOrder.Lex)
    {
        var names = new HashSet<string>(eliminated.Select(v => v.Name), StringComparer.Ordinal);
        var basis = Basis(generators, order);
        return basis.Where(p => FreeOfVariables(p, names)).ToList();
    }

    /// <summary>True when no term of p mentions any of the given variables (by exponent, not
    /// by the variable order, which always carries the full ring).</summary>
    private static bool FreeOfVariables(Polynomial p, HashSet<string> names)
    {
        var indices = names
            .Select(n => p.Order.IndexOf(n))
            .Where(i => i >= 0)
            .ToList();
        foreach (var (m, _) in p.Terms)
        {
            foreach (var i in indices)
            {
                if (i < m.Exps.Length && m.Exps[i] != 0)
                    return false;
            }
        }
        return true;
    }

    private static Polynomial Monic(Polynomial p)
    {
        if (p.IsZero)
            return p;
        var lc = p.LeadingCoefficient(MonomialOrder.Lex);
        if (lc.IsOne)
            return p;
        var r = new Polynomial(p.Order);
        foreach (var (m, c) in p.Terms)
            r = Polynomial.Add(r, Polynomial.FromMonomial(p.Order, m, c / lc));
        return r;
    }

    private static (Monomial Monomial, Rat Coefficient) LeadingTerm(Polynomial p, MonomialComparer cmp)
    {
        Monomial best = null!;
        Rat bestC = Rat.Zero;
        bool first = true;
        foreach (var (m, c) in p.Terms)
        {
            if (first || cmp.Compare(m, best) > 0)
            {
                best = m;
                bestC = c;
                first = false;
            }
        }
        return (best, bestC);
    }

    private static Polynomial SPolynomial(Polynomial f, Polynomial g, MonomialComparer cmp)
    {
        var (lf, cf) = LeadingTerm(f, cmp);
        var (lg, cg) = LeadingTerm(g, cmp);
        var lcm = LcmMonomial(lf, lg);
        var mf = DivideMonomial(lcm, lf);
        var mg = DivideMonomial(lcm, lg);
        var left = Polynomial.Multiply(Polynomial.FromMonomial(f.Order, mf, Rat.One / cf), f);
        var right = Polynomial.Multiply(Polynomial.FromMonomial(g.Order, mg, Rat.One / cg), g);
        return Polynomial.Subtract(left, right);
    }

    private static Polynomial ReduceBy(Polynomial p, IReadOnlyList<Polynomial> basis, MonomialComparer cmp)
    {
        var r = new Polynomial(p.Order);
        var cur = p;
        while (!cur.IsZero)
        {
            Lovelace.Abstractions.Cancellation.ThrowIfCancellationRequested();
            var (lt, lc) = LeadingTerm(cur, cmp);
            bool reduced = false;
            foreach (var b in basis)
            {
                if (b.IsZero)
                    continue;
                var (bl, bc) = LeadingTerm(b, cmp);
                if (Divisible(lt, bl))
                {
                    var qm = DivideMonomial(lt, bl);
                    var q = Polynomial.FromMonomial(cur.Order, qm, lc / bc);
                    cur = Polynomial.Subtract(cur, Polynomial.Multiply(q, b));
                    reduced = true;
                    break;
                }
            }
            if (!reduced)
            {
                r = Polynomial.Add(r, Polynomial.FromMonomial(cur.Order, lt, lc));
                cur = Polynomial.Subtract(cur, Polynomial.FromMonomial(cur.Order, lt, lc));
            }
        }
        return r;
    }

    private static List<Polynomial> Interreduce(List<Polynomial> basis, MonomialComparer cmp)
    {
        var result = new List<Polynomial>();
        for (int i = 0; i < basis.Count; i++)
        {
            var others = basis.Where((_, idx) => idx != i).ToList();
            var r = ReduceBy(basis[i], others, cmp);
            if (!r.IsZero)
                result.Add(Monic(r));
        }
        result.Sort((a, b) =>
        {
            var (ma, _) = LeadingTerm(a, cmp);
            var (mb, _) = LeadingTerm(b, cmp);
            return cmp.Compare(ma, mb);
        });
        return result;
    }

    private static Monomial LcmMonomial(Monomial a, Monomial b)
    {
        int n = Math.Max(a.Exps.Length, b.Exps.Length);
        var e = new int[n];
        for (int i = 0; i < n; i++)
        {
            int ea = i < a.Exps.Length ? a.Exps[i] : 0;
            int eb = i < b.Exps.Length ? b.Exps[i] : 0;
            e[i] = Math.Max(ea, eb);
        }
        return new Monomial(e);
    }

    private static Monomial DivideMonomial(Monomial a, Monomial b)
    {
        int n = Math.Max(a.Exps.Length, b.Exps.Length);
        var e = new int[n];
        for (int i = 0; i < n; i++)
        {
            int ea = i < a.Exps.Length ? a.Exps[i] : 0;
            int eb = i < b.Exps.Length ? b.Exps[i] : 0;
            e[i] = ea - eb;
        }
        return new Monomial(e);
    }

    private static bool Divisible(Monomial a, Monomial b)
    {
        int n = Math.Max(a.Exps.Length, b.Exps.Length);
        for (int i = 0; i < n; i++)
        {
            int ea = i < a.Exps.Length ? a.Exps[i] : 0;
            int eb = i < b.Exps.Length ? b.Exps[i] : 0;
            if (ea < eb)
                return false;
        }
        return true;
    }
}
