<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lovelace.Array\Lovelace.Array.csproj" />
    <ProjectReference Include="..\Lovelace.Natural\Lovelace.Natural.csproj" />
    <ProjectReference Include="..\Lovelace.Integer\Lovelace.Integer.csproj" />
    <ProjectReference Include="..\Lovelace.Real\Lovelace.Real.csproj" />
  </ItemGroup>

</Project>
