@echo off
"C:\Users\ricar\dev\LovelaceSharp\out\aot\Lovelace.Run.exe" --file C:\Users\ricar\dev\LovelaceSharp\docs\goal-cycle-6\round-23\r23-R\ls\c11.ls > C:\Users\ricar\dev\LovelaceSharp\docs\goal-cycle-6\round-23\r23-R\raw\c11.out 2> C:\Users\ricar\dev\LovelaceSharp\docs\goal-cycle-6\round-23\r23-R\raw\c11.err & echo %ERRORLEVEL% > C:\Users\ricar\dev\LovelaceSharp\docs\goal-cycle-6\round-23\r23-R\raw\c11.rc
"C:\Users\ricar\dev\LovelaceSharp\out\aot\Lovelace.Run.exe" --file C:\Users\ricar\dev\LovelaceSharp\docs\goal-cycle-6\round-23\r23-R\ls\c36.ls > C:\Users\ricar\dev\LovelaceSharp\docs\goal-cycle-6\round-23\r23-R\raw\c36.out 2> C:\Users\ricar\dev\LovelaceSharp\docs\goal-cycle-6\round-23\r23-R\raw\c36.err & echo %ERRORLEVEL% > C:\Users\ricar\dev\LovelaceSharp\docs\goal-cycle-6\round-23\r23-R\raw\c36.rc
"C:\Users\ricar\dev\LovelaceSharp\out\aot\Lovelace.Run.exe" --file C:\Users\ricar\dev\LovelaceSharp\docs\goal-cycle-6\round-23\r23-R\ls\c37.ls > C:\Users\ricar\dev\LovelaceSharp\docs\goal-cycle-6\round-23\r23-R\raw\c37.out 2> C:\Users\ricar\dev\LovelaceSharp\docs\goal-cycle-6\round-23\r23-R\raw\c37.err & echo %ERRORLEVEL% > C:\Users\ricar\dev\LovelaceSharp\docs\goal-cycle-6\round-23\r23-R\raw\c37.rc
"C:\Users\ricar\dev\LovelaceSharp\out\aot\Lovelace.Run.exe" --file C:\Users\ricar\dev\LovelaceSharp\docs\goal-cycle-6\round-23\r23-R\ls\c38.ls --print-budget 20 > C:\Users\ricar\dev\LovelaceSharp\docs\goal-cycle-6\round-23\r23-R\raw\c38.out 2> C:\Users\ricar\dev\LovelaceSharp\docs\goal-cycle-6\round-23\r23-R\raw\c38.err & echo %ERRORLEVEL% > C:\Users\ricar\dev\LovelaceSharp\docs\goal-cycle-6\round-23\r23-R\raw\c38.rc
"C:\Users\ricar\dev\LovelaceSharp\out\aot\Lovelace.Run.exe" --file C:\Users\ricar\dev\LovelaceSharp\docs\goal-cycle-6\round-23\r23-R\ls\c38.ls > C:\Users\ricar\dev\LovelaceSharp\docs\goal-cycle-6\round-23\r23-R\raw\c39.out 2> C:\Users\ricar\dev\LovelaceSharp\docs\goal-cycle-6\round-23\r23-R\raw\c39.err & echo %ERRORLEVEL% > C:\Users\ricar\dev\LovelaceSharp\docs\goal-cycle-6\round-23\r23-R\raw\c39.rc
"C:\Users\ricar\dev\LovelaceSharp\out\aot\Lovelace.Run.exe" --file C:\Users\ricar\dev\LovelaceSharp\docs\goal-cycle-6\round-23\r23-R\ls\r0.ls > C:\Users\ricar\dev\LovelaceSharp\docs\goal-cycle-6\round-23\r23-R\raw\r0.out 2> C:\Users\ricar\dev\LovelaceSharp\docs\goal-cycle-6\round-23\r23-R\raw\r0.err & echo %ERRORLEVEL% > C:\Users\ricar\dev\LovelaceSharp\docs\goal-cycle-6\round-23\r23-R\raw\r0.rc
"C:\Users\ricar\dev\LovelaceSharp\out\aot\Lovelace.Run.exe" --file C:\Users\ricar\dev\LovelaceSharp\docs\goal-cycle-6\round-23\r23-R\ls\r1.ls > C:\Users\ricar\dev\LovelaceSharp\docs\goal-cycle-6\round-23\r23-R\raw\r1.out 2> C:\Users\ricar\dev\LovelaceSharp\docs\goal-cycle-6\round-23\r23-R\raw\r1.err & echo %ERRORLEVEL% > C:\Users\ricar\dev\LovelaceSharp\docs\goal-cycle-6\round-23\r23-R\raw\r1.rc
"C:\Users\ricar\dev\LovelaceSharp\out\aot\Lovelace.Run.exe" --file C:\Users\ricar\dev\LovelaceSharp\docs\goal-cycle-6\round-23\r23-R\ls\r-canon.ls > C:\Users\ricar\dev\LovelaceSharp\docs\goal-cycle-6\round-23\r23-R\raw\rcanon.out 2> C:\Users\ricar\dev\LovelaceSharp\docs\goal-cycle-6\round-23\r23-R\raw\rcanon.err & echo %ERRORLEVEL% > C:\Users\ricar\dev\LovelaceSharp\docs\goal-cycle-6\round-23\r23-R\raw\rcanon.rc
